apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bhandar-setu-backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - image: gcr.io/bhandar-setu-prod/backend:latest
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          env:
            - name: ENVIRONMENT
              value: "production"
